version: '3'

volumes:
  data:

services:
  web:
    image: 'tutum/apache-php'
    container_name: apache
    ports:
      - "8080:80"
    volumes:
      - /home/rhuan.santos@db1.com.br/Projeto/SiteProdutos:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3307:3307"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development

  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
